version: '3'
services:
  tan-node-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: drtan/province-api:2.1.0
    container_name: tan-api
    ports:
      - "3000:3000"
    restart: unless-stopped
    tty: true
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - tan-mysql-service
    networks:
      - tan-network


  tan-mysql-service:
    image: mysql:latest
    container_name: tan-mysql-province
    volumes:
      #- c:/mysql/ThProvince:/var/lib/mysql
      - ./create_provincedb.sql:/docker-entrypoint-initdb.d/create_provincedb.sql
    restart: unless-stopped
    #tty: true
    environment:
      - MYSQL_DATABASE=ProvinceDB
      - MYSQL_ROOT_PASSWORD=toor
      - LANG=C.UTF-8
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - tan-network

networks:
  tan-network:
    driver: bridge
