version: '3'
services:
  tan-mysql-service:
    image: mysql:5.7
    container_name: tan-mysql-province
    volumes:
      #- c:/mysql/ThProvince:/var/lib/mysql
      - ./db_test.sql:/docker-entrypoint-initdb.d/db_test.sql
    restart: unless-stopped
    #tty: true
    environment:
      - MYSQL_DATABASE=ProvinceDB
      - MYSQL_ROOT_PASSWORD=toor
      - LANG=C.UTF-8
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "13306:3306"
    networks:
      - tan-network

networks:
  tan-network:
    driver: bridge
